# Generated by Django 4.0.6 on 2022-07-24 23:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(default='Checkings Account', max_length=150),
        ),
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='is_budget',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='title',
            field=models.CharField(default='Bucket', max_length=150),
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_revenue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Item', max_length=150),
        ),
    ]
