# Generated by Django 4.1 on 2022-08-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_alter_item_date_incurred"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucket",
            name="budget_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
