# Generated by Django 4.1 on 2022-08-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_alter_bucket_budget_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_revenue",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bucket", name="title", field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="item", name="title", field=models.CharField(max_length=150),
        ),
    ]
